#!/usr/bin/env bash
# RealtimePi script
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

set -x
set -e

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

# wget https://github.com/kdoren/linux/releases/download/rpi_5.15.65/linux-image-5.15.65-llat-v7l+_5.15.65-1_armhf.deb
# wget https://github.com/kdoren/linux/releases/download/rpi_5.15.65/linux-libc-dev_5.15.65-1_armhf.deb
wget https://github.com/kdoren/linux/releases/download/rpi_5.15.65-rt49/linux-image-5.15.65-rt49-v7l+_5.15.65-1_armhf.deb
wget https://github.com/kdoren/linux/releases/download/rpi_5.15.65-rt49/linux-libc-dev_5.15.65-1_armhf.deb

dpkg -i *.deb

KERN=5.15.65-rt49-v7l+
mkdir -p /boot/$KERN/overlays/
cp -d /usr/lib/linux-image-$KERN/overlays/* /boot/$KERN/overlays/
cp -dr /usr/lib/linux-image-$KERN/* /boot/$KERN/
touch /boot/$KERN/overlays/README
mv /boot/vmlinuz-$KERN /boot/$KERN/
mv /boot/System.map-$KERN /boot/$KERN/
cp /boot/config-$KERN /boot/$KERN/
cat >> /boot/config.txt << EOF

[all]
kernel=vmlinuz-$KERN
# initramfs initrd.img-$KERN
os_prefix=$KERN/
overlay_prefix=overlays/
[all]
EOF

rm -v *.deb

